#!/usr/bin/env bash

set -euo pipefail

if [ $# -eq 0 ]
then
  echo "Please specify a subcommand"
  exit 1
fi

case $1 in
  "waiting")
    shift
    ./waiting.bash $@
    ;;
  "approve")
    shift
    ./approve.bash $@
    ;;
  "comment")
    shift
    ./comment.bash $@
    ;;
  "show")
    shift
    ./show.bash $@
    ;;
  *)
    echo "Unknown option $1"
    exit 1
    ;;
esac
